package de.handler.mobile.android.shopprototype.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CATEGORY.
*/
public class CategoryDao extends AbstractDao<Category, Long> {

    public static final String TABLENAME = "CATEGORY";

    /**
     * Properties of entity Category.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Desc = new Property(2, String.class, "desc", false, "DESC");
        public final static Property Parent_id = new Property(3, Integer.class, "parent_id", false, "PARENT_ID");
        public final static Property Lft = new Property(4, Integer.class, "lft", false, "LFT");
        public final static Property Rgt = new Property(5, Integer.class, "rgt", false, "RGT");
        public final static Property Depth = new Property(6, Integer.class, "depth", false, "DEPTH");
        public final static Property Children_count = new Property(7, Integer.class, "children_count", false, "CHILDREN_COUNT");
        public final static Property Weight = new Property(8, Integer.class, "weight", false, "WEIGHT");
        public final static Property View_columns = new Property(9, Integer.class, "view_columns", false, "VIEW_COLUMNS");
        public final static Property Slug = new Property(10, String.class, "slug", false, "SLUG");
    };

    private DaoSession daoSession;


    public CategoryDao(DaoConfig config) {
        super(config);
    }
    
    public CategoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CATEGORY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'DESC' TEXT," + // 2: desc
                "'PARENT_ID' INTEGER," + // 3: parent_id
                "'LFT' INTEGER," + // 4: lft
                "'RGT' INTEGER," + // 5: rgt
                "'DEPTH' INTEGER," + // 6: depth
                "'CHILDREN_COUNT' INTEGER," + // 7: children_count
                "'WEIGHT' INTEGER," + // 8: weight
                "'VIEW_COLUMNS' INTEGER," + // 9: view_columns
                "'SLUG' TEXT);"); // 10: slug
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CATEGORY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Category entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(3, desc);
        }
 
        Integer parent_id = entity.getParent_id();
        if (parent_id != null) {
            stmt.bindLong(4, parent_id);
        }
 
        Integer lft = entity.getLft();
        if (lft != null) {
            stmt.bindLong(5, lft);
        }
 
        Integer rgt = entity.getRgt();
        if (rgt != null) {
            stmt.bindLong(6, rgt);
        }
 
        Integer depth = entity.getDepth();
        if (depth != null) {
            stmt.bindLong(7, depth);
        }
 
        Integer children_count = entity.getChildren_count();
        if (children_count != null) {
            stmt.bindLong(8, children_count);
        }
 
        Integer weight = entity.getWeight();
        if (weight != null) {
            stmt.bindLong(9, weight);
        }
 
        Integer view_columns = entity.getView_columns();
        if (view_columns != null) {
            stmt.bindLong(10, view_columns);
        }
 
        String slug = entity.getSlug();
        if (slug != null) {
            stmt.bindString(11, slug);
        }
    }

    @Override
    protected void attachEntity(Category entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Category readEntity(Cursor cursor, int offset) {
        Category entity = new Category( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // desc
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // parent_id
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // lft
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // rgt
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // depth
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // children_count
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // weight
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // view_columns
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // slug
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Category entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDesc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setParent_id(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setLft(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setRgt(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setDepth(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setChildren_count(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setWeight(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setView_columns(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setSlug(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Category entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Category entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
