package de.handler.mobile.android.shopprototype.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.os.Parcel;
import android.os.Parcelable;

import java.util.Date;

// KEEP INCLUDES END

/**
 * Entity mapped to table IMAGE.
 */
public class Image implements android.os.Parcelable {

    private Long id;
    private String image_file_name;
    private String image_content_type;
    private Integer image_file_size;
    private java.util.Date image_updated_at;
    private java.util.Date created_at;
    private java.util.Date updated_at;
    private Integer imageable_id;
    private String type;
    private Boolean is_title;
    private String external_url;
    private Boolean image_processing;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Image() {
    }

    public Image(Long id) {
        this.id = id;
    }

    public Image(Long id, String image_file_name, String image_content_type, Integer image_file_size, java.util.Date image_updated_at, java.util.Date created_at, java.util.Date updated_at, Integer imageable_id, String type, Boolean is_title, String external_url, Boolean image_processing) {
        this.id = id;
        this.image_file_name = image_file_name;
        this.image_content_type = image_content_type;
        this.image_file_size = image_file_size;
        this.image_updated_at = image_updated_at;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.imageable_id = imageable_id;
        this.type = type;
        this.is_title = is_title;
        this.external_url = external_url;
        this.image_processing = image_processing;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImage_file_name() {
        return image_file_name;
    }

    public void setImage_file_name(String image_file_name) {
        this.image_file_name = image_file_name;
    }

    public String getImage_content_type() {
        return image_content_type;
    }

    public void setImage_content_type(String image_content_type) {
        this.image_content_type = image_content_type;
    }

    public Integer getImage_file_size() {
        return image_file_size;
    }

    public void setImage_file_size(Integer image_file_size) {
        this.image_file_size = image_file_size;
    }

    public java.util.Date getImage_updated_at() {
        return image_updated_at;
    }

    public void setImage_updated_at(java.util.Date image_updated_at) {
        this.image_updated_at = image_updated_at;
    }

    public java.util.Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(java.util.Date created_at) {
        this.created_at = created_at;
    }

    public java.util.Date getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(java.util.Date updated_at) {
        this.updated_at = updated_at;
    }

    public Integer getImageable_id() {
        return imageable_id;
    }

    public void setImageable_id(Integer imageable_id) {
        this.imageable_id = imageable_id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Boolean getIs_title() {
        return is_title;
    }

    public void setIs_title(Boolean is_title) {
        this.is_title = is_title;
    }

    public String getExternal_url() {
        return external_url;
    }

    public void setExternal_url(String external_url) {
        this.external_url = external_url;
    }

    public Boolean getImage_processing() {
        return image_processing;
    }

    public void setImage_processing(Boolean image_processing) {
        this.image_processing = image_processing;
    }


    // KEEP METHODS - put your custom methods here
    public Image(Parcel dest) {
        id = dest.readLong();
        image_file_name = dest.readString();
        image_content_type = dest.readString();
        image_file_size = dest.readInt();
        image_updated_at = new Date(dest.readLong());
        created_at = new Date(dest.readLong());
        updated_at = new Date(dest.readLong());
        imageable_id = dest.readInt();
        type = dest.readString();
        is_title = dest.readByte() != 0;
        external_url = dest.readString();
        image_processing = dest.readByte() != 0;
    }


    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(id);
        dest.writeString(image_file_name);
        dest.writeString(image_content_type);
        dest.writeInt(image_file_size);
        dest.writeLong(image_updated_at.getTime());
        dest.writeLong(created_at.getTime());
        dest.writeLong(updated_at.getTime());
        dest.writeInt(imageable_id);
        dest.writeString(type);
        dest.writeByte((byte) (is_title ? 1:0));
        dest.writeString(external_url);
        dest.writeByte((byte) (image_processing ? 0:1));
    }

    public static final Parcelable.Creator<Image> CREATOR
            = new Parcelable.Creator<Image>() {
        public Image createFromParcel(Parcel in) {
            return new Image(in);
        }

        public Image[] newArray(int size) {
            return new Image[size];
        }
    };
    // KEEP METHODS END
}
