package de.handler.mobile.android.shopprototype.datasource.database;


import android.os.Parcel;
import android.os.Parcelable;

import java.util.Date;
import java.util.List;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS
// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PRODUCT.
 */
public class Product implements android.os.Parcelable {

    private Long id;
    private String title = "";
    private String content = "";
    /** Not-null value. */
    private java.util.Date created_at = new Date();
    /** Not-null value. */
    private java.util.Date updated_at = new Date();
    private Integer user_id = 0;
    private String condition = "";
    private Integer price_cents = 0;
    private String currency = "";
    private Boolean fair = false;
    private String fair_kind = "";
    private String fair_seal = "";
    private Boolean ecologic = false;
    private String ecologic_seal = "";
    private Boolean small_and_precious = false;
    private String small_and_precious_reason = "";
    private Boolean small_and_precious_handmade = false;
    private Integer quantity = 0;
    private String transport_details = "";
    private String payment_details = "";
    private Integer friendly_percent = 0;
    private int calculated_fair_cents = 0;
    private int calculated_friendly_cents = 0;
    private int calculated_fee_cents = 0;
    private String condition_extra = "";
    private Boolean small_and_precious_eu_small_enterprise = false;
    private String ecologic_kind = "";
    private String upcycling_reason = "";
    private String slug = "";
    private Boolean transport_pickup = false;
    private Boolean transport_type1 = false;
    private Boolean transport_type2 = false;
    private String transport_type1_provider = "";
    private String transport_type2_provider = "";
    private int transport_type1_price_cents = 0;
    private int transport_type2_price_cents = 0;
    private Boolean payment_bank_transfer = false;
    private Boolean payment_cash = false;
    private Boolean payment_paypal = false;
    private Boolean payment_cash_on_delivery = false;
    private Boolean payment_invoice = false;
    private int payment_cash_on_delivery_price_cents = 0;
    private Integer basic_price_cents = 0;
    private String basic_price_amount = "";
    private String state = "";
    private Integer vat = 0;
    private String custom_seller_identifier = "";
    private String gtin = "";
    private Integer transport_type1_number = 0;
    private Integer transport_type2_number = 0;
    private Integer discount_id = 0;
    private Integer friendly_percent_organisation_id = 0;
    private String article_template_name = "";
    private String transport_time = "";
    private Integer quantity_available = 0;
    private Boolean unified_transport = false;
    private Boolean swappable = false;
    private Boolean borrowable = false;
    private Integer comments_count = 0;
    private Integer original_id = 0;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ProductDao myDao;

    private List<ProductCategory> productCategories;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Product() {
    }

    public Product(Long id) {
        this.id = id;
    }

    public Product(Long id, String title, String content, java.util.Date created_at, java.util.Date updated_at, Integer user_id, String condition, Integer price_cents, String currency, Boolean fair, String fair_kind, String fair_seal, Boolean ecologic, String ecologic_seal, Boolean small_and_precious, String small_and_precious_reason, Boolean small_and_precious_handmade, Integer quantity, String transport_details, String payment_details, Integer friendly_percent, int calculated_fair_cents, int calculated_friendly_cents, int calculated_fee_cents, String condition_extra, Boolean small_and_precious_eu_small_enterprise, String ecologic_kind, String upcycling_reason, String slug, Boolean transport_pickup, Boolean transport_type1, Boolean transport_type2, String transport_type1_provider, String transport_type2_provider, int transport_type1_price_cents, int transport_type2_price_cents, Boolean payment_bank_transfer, Boolean payment_cash, Boolean payment_paypal, Boolean payment_cash_on_delivery, Boolean payment_invoice, int payment_cash_on_delivery_price_cents, Integer basic_price_cents, String basic_price_amount, String state, Integer vat, String custom_seller_identifier, String gtin, Integer transport_type1_number, Integer transport_type2_number, Integer discount_id, Integer friendly_percent_organisation_id, String article_template_name, String transport_time, Integer quantity_available, Boolean unified_transport, Boolean swappable, Boolean borrowable, Integer comments_count, Integer original_id) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.user_id = user_id;
        this.condition = condition;
        this.price_cents = price_cents;
        this.currency = currency;
        this.fair = fair;
        this.fair_kind = fair_kind;
        this.fair_seal = fair_seal;
        this.ecologic = ecologic;
        this.ecologic_seal = ecologic_seal;
        this.small_and_precious = small_and_precious;
        this.small_and_precious_reason = small_and_precious_reason;
        this.small_and_precious_handmade = small_and_precious_handmade;
        this.quantity = quantity;
        this.transport_details = transport_details;
        this.payment_details = payment_details;
        this.friendly_percent = friendly_percent;
        this.calculated_fair_cents = calculated_fair_cents;
        this.calculated_friendly_cents = calculated_friendly_cents;
        this.calculated_fee_cents = calculated_fee_cents;
        this.condition_extra = condition_extra;
        this.small_and_precious_eu_small_enterprise = small_and_precious_eu_small_enterprise;
        this.ecologic_kind = ecologic_kind;
        this.upcycling_reason = upcycling_reason;
        this.slug = slug;
        this.transport_pickup = transport_pickup;
        this.transport_type1 = transport_type1;
        this.transport_type2 = transport_type2;
        this.transport_type1_provider = transport_type1_provider;
        this.transport_type2_provider = transport_type2_provider;
        this.transport_type1_price_cents = transport_type1_price_cents;
        this.transport_type2_price_cents = transport_type2_price_cents;
        this.payment_bank_transfer = payment_bank_transfer;
        this.payment_cash = payment_cash;
        this.payment_paypal = payment_paypal;
        this.payment_cash_on_delivery = payment_cash_on_delivery;
        this.payment_invoice = payment_invoice;
        this.payment_cash_on_delivery_price_cents = payment_cash_on_delivery_price_cents;
        this.basic_price_cents = basic_price_cents;
        this.basic_price_amount = basic_price_amount;
        this.state = state;
        this.vat = vat;
        this.custom_seller_identifier = custom_seller_identifier;
        this.gtin = gtin;
        this.transport_type1_number = transport_type1_number;
        this.transport_type2_number = transport_type2_number;
        this.discount_id = discount_id;
        this.friendly_percent_organisation_id = friendly_percent_organisation_id;
        this.article_template_name = article_template_name;
        this.transport_time = transport_time;
        this.quantity_available = quantity_available;
        this.unified_transport = unified_transport;
        this.swappable = swappable;
        this.borrowable = borrowable;
        this.comments_count = comments_count;
        this.original_id = original_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getProductDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    /** Not-null value. */
    public java.util.Date getCreated_at() {
        return created_at;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated_at(java.util.Date created_at) {
        this.created_at = created_at;
    }

    /** Not-null value. */
    public java.util.Date getUpdated_at() {
        return updated_at;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdated_at(java.util.Date updated_at) {
        this.updated_at = updated_at;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public String getCondition() {
        return condition;
    }

    public void setCondition(String condition) {
        this.condition = condition;
    }

    public Integer getPrice_cents() {
        return price_cents;
    }

    public void setPrice_cents(Integer price_cents) {
        this.price_cents = price_cents;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Boolean getFair() {
        return fair;
    }

    public void setFair(Boolean fair) {
        this.fair = fair;
    }

    public String getFair_kind() {
        return fair_kind;
    }

    public void setFair_kind(String fair_kind) {
        this.fair_kind = fair_kind;
    }

    public String getFair_seal() {
        return fair_seal;
    }

    public void setFair_seal(String fair_seal) {
        this.fair_seal = fair_seal;
    }

    public Boolean getEcologic() {
        return ecologic;
    }

    public void setEcologic(Boolean ecologic) {
        this.ecologic = ecologic;
    }

    public String getEcologic_seal() {
        return ecologic_seal;
    }

    public void setEcologic_seal(String ecologic_seal) {
        this.ecologic_seal = ecologic_seal;
    }

    public Boolean getSmall_and_precious() {
        return small_and_precious;
    }

    public void setSmall_and_precious(Boolean small_and_precious) {
        this.small_and_precious = small_and_precious;
    }

    public String getSmall_and_precious_reason() {
        return small_and_precious_reason;
    }

    public void setSmall_and_precious_reason(String small_and_precious_reason) {
        this.small_and_precious_reason = small_and_precious_reason;
    }

    public Boolean getSmall_and_precious_handmade() {
        return small_and_precious_handmade;
    }

    public void setSmall_and_precious_handmade(Boolean small_and_precious_handmade) {
        this.small_and_precious_handmade = small_and_precious_handmade;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public String getTransport_details() {
        return transport_details;
    }

    public void setTransport_details(String transport_details) {
        this.transport_details = transport_details;
    }

    public String getPayment_details() {
        return payment_details;
    }

    public void setPayment_details(String payment_details) {
        this.payment_details = payment_details;
    }

    public Integer getFriendly_percent() {
        return friendly_percent;
    }

    public void setFriendly_percent(Integer friendly_percent) {
        this.friendly_percent = friendly_percent;
    }

    public int getCalculated_fair_cents() {
        return calculated_fair_cents;
    }

    public void setCalculated_fair_cents(int calculated_fair_cents) {
        this.calculated_fair_cents = calculated_fair_cents;
    }

    public int getCalculated_friendly_cents() {
        return calculated_friendly_cents;
    }

    public void setCalculated_friendly_cents(int calculated_friendly_cents) {
        this.calculated_friendly_cents = calculated_friendly_cents;
    }

    public int getCalculated_fee_cents() {
        return calculated_fee_cents;
    }

    public void setCalculated_fee_cents(int calculated_fee_cents) {
        this.calculated_fee_cents = calculated_fee_cents;
    }

    public String getCondition_extra() {
        return condition_extra;
    }

    public void setCondition_extra(String condition_extra) {
        this.condition_extra = condition_extra;
    }

    public Boolean getSmall_and_precious_eu_small_enterprise() {
        return small_and_precious_eu_small_enterprise;
    }

    public void setSmall_and_precious_eu_small_enterprise(Boolean small_and_precious_eu_small_enterprise) {
        this.small_and_precious_eu_small_enterprise = small_and_precious_eu_small_enterprise;
    }

    public String getEcologic_kind() {
        return ecologic_kind;
    }

    public void setEcologic_kind(String ecologic_kind) {
        this.ecologic_kind = ecologic_kind;
    }

    public String getUpcycling_reason() {
        return upcycling_reason;
    }

    public void setUpcycling_reason(String upcycling_reason) {
        this.upcycling_reason = upcycling_reason;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public Boolean getTransport_pickup() {
        return transport_pickup;
    }

    public void setTransport_pickup(Boolean transport_pickup) {
        this.transport_pickup = transport_pickup;
    }

    public Boolean getTransport_type1() {
        return transport_type1;
    }

    public void setTransport_type1(Boolean transport_type1) {
        this.transport_type1 = transport_type1;
    }

    public Boolean getTransport_type2() {
        return transport_type2;
    }

    public void setTransport_type2(Boolean transport_type2) {
        this.transport_type2 = transport_type2;
    }

    public String getTransport_type1_provider() {
        return transport_type1_provider;
    }

    public void setTransport_type1_provider(String transport_type1_provider) {
        this.transport_type1_provider = transport_type1_provider;
    }

    public String getTransport_type2_provider() {
        return transport_type2_provider;
    }

    public void setTransport_type2_provider(String transport_type2_provider) {
        this.transport_type2_provider = transport_type2_provider;
    }

    public int getTransport_type1_price_cents() {
        return transport_type1_price_cents;
    }

    public void setTransport_type1_price_cents(int transport_type1_price_cents) {
        this.transport_type1_price_cents = transport_type1_price_cents;
    }

    public int getTransport_type2_price_cents() {
        return transport_type2_price_cents;
    }

    public void setTransport_type2_price_cents(int transport_type2_price_cents) {
        this.transport_type2_price_cents = transport_type2_price_cents;
    }

    public Boolean getPayment_bank_transfer() {
        return payment_bank_transfer;
    }

    public void setPayment_bank_transfer(Boolean payment_bank_transfer) {
        this.payment_bank_transfer = payment_bank_transfer;
    }

    public Boolean getPayment_cash() {
        return payment_cash;
    }

    public void setPayment_cash(Boolean payment_cash) {
        this.payment_cash = payment_cash;
    }

    public Boolean getPayment_paypal() {
        return payment_paypal;
    }

    public void setPayment_paypal(Boolean payment_paypal) {
        this.payment_paypal = payment_paypal;
    }

    public Boolean getPayment_cash_on_delivery() {
        return payment_cash_on_delivery;
    }

    public void setPayment_cash_on_delivery(Boolean payment_cash_on_delivery) {
        this.payment_cash_on_delivery = payment_cash_on_delivery;
    }

    public Boolean getPayment_invoice() {
        return payment_invoice;
    }

    public void setPayment_invoice(Boolean payment_invoice) {
        this.payment_invoice = payment_invoice;
    }

    public int getPayment_cash_on_delivery_price_cents() {
        return payment_cash_on_delivery_price_cents;
    }

    public void setPayment_cash_on_delivery_price_cents(int payment_cash_on_delivery_price_cents) {
        this.payment_cash_on_delivery_price_cents = payment_cash_on_delivery_price_cents;
    }

    public Integer getBasic_price_cents() {
        return basic_price_cents;
    }

    public void setBasic_price_cents(Integer basic_price_cents) {
        this.basic_price_cents = basic_price_cents;
    }

    public String getBasic_price_amount() {
        return basic_price_amount;
    }

    public void setBasic_price_amount(String basic_price_amount) {
        this.basic_price_amount = basic_price_amount;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Integer getVat() {
        return vat;
    }

    public void setVat(Integer vat) {
        this.vat = vat;
    }

    public String getCustom_seller_identifier() {
        return custom_seller_identifier;
    }

    public void setCustom_seller_identifier(String custom_seller_identifier) {
        this.custom_seller_identifier = custom_seller_identifier;
    }

    public String getGtin() {
        return gtin;
    }

    public void setGtin(String gtin) {
        this.gtin = gtin;
    }

    public Integer getTransport_type1_number() {
        return transport_type1_number;
    }

    public void setTransport_type1_number(Integer transport_type1_number) {
        this.transport_type1_number = transport_type1_number;
    }

    public Integer getTransport_type2_number() {
        return transport_type2_number;
    }

    public void setTransport_type2_number(Integer transport_type2_number) {
        this.transport_type2_number = transport_type2_number;
    }

    public Integer getDiscount_id() {
        return discount_id;
    }

    public void setDiscount_id(Integer discount_id) {
        this.discount_id = discount_id;
    }

    public Integer getFriendly_percent_organisation_id() {
        return friendly_percent_organisation_id;
    }

    public void setFriendly_percent_organisation_id(Integer friendly_percent_organisation_id) {
        this.friendly_percent_organisation_id = friendly_percent_organisation_id;
    }

    public String getArticle_template_name() {
        return article_template_name;
    }

    public void setArticle_template_name(String article_template_name) {
        this.article_template_name = article_template_name;
    }

    public String getTransport_time() {
        return transport_time;
    }

    public void setTransport_time(String transport_time) {
        this.transport_time = transport_time;
    }

    public Integer getQuantity_available() {
        return quantity_available;
    }

    public void setQuantity_available(Integer quantity_available) {
        this.quantity_available = quantity_available;
    }

    public Boolean getUnified_transport() {
        return unified_transport;
    }

    public void setUnified_transport(Boolean unified_transport) {
        this.unified_transport = unified_transport;
    }

    public Boolean getSwappable() {
        return swappable;
    }

    public void setSwappable(Boolean swappable) {
        this.swappable = swappable;
    }

    public Boolean getBorrowable() {
        return borrowable;
    }

    public void setBorrowable(Boolean borrowable) {
        this.borrowable = borrowable;
    }

    public Integer getComments_count() {
        return comments_count;
    }

    public void setComments_count(Integer comments_count) {
        this.comments_count = comments_count;
    }

    public Integer getOriginal_id() {
        return original_id;
    }

    public void setOriginal_id(Integer original_id) {
        this.original_id = original_id;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<ProductCategory> getProductCategories() {
        if (productCategories == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ProductCategoryDao targetDao = daoSession.getProductCategoryDao();
            List<ProductCategory> productCategoriesNew = targetDao._queryProduct_ProductCategories(id);
            synchronized (this) {
                if(productCategories == null) {
                    productCategories = productCategoriesNew;
                }
            }
        }
        return productCategories;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetProductCategories() {
        productCategories = null;
    }

    /** Convenient call for . Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for . Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for . Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }


    // KEEP METHODS - put your custom methods here
    public Product(Parcel dest) {
        id = dest.readLong();
        title = dest.readString();
        content = dest.readString();
        created_at = new Date(dest.readLong());
        updated_at = new Date(dest.readLong());
        user_id = dest.readInt();
        condition = dest.readString();
        price_cents = dest.readInt();
        currency = dest.readString();
        fair = dest.readByte() != 0;
        fair_kind = dest.readString();
        fair_seal = dest.readString();
        ecologic = dest.readByte() != 0;
        ecologic_seal = dest.readString();
        ecologic_kind = dest.readString();
        small_and_precious = dest.readByte() != 0;
        small_and_precious_reason = dest.readString();
        small_and_precious_handmade = dest.readByte() != 0;
        quantity = dest.readInt();
        transport_details = dest.readString();
        payment_details = dest.readString();
        friendly_percent = dest.readInt();
        calculated_fair_cents = dest.readInt();
        calculated_friendly_cents = dest.readInt();
        calculated_fee_cents = dest.readInt();
        condition_extra = dest.readString();
        small_and_precious_eu_small_enterprise = dest.readByte() != 0;
        upcycling_reason = dest.readString();
        slug = dest.readString();

        transport_pickup = dest.readByte() != 0;
        transport_type1 = dest.readByte() != 0;
        transport_type2 = dest.readByte() != 0;
        transport_type1_provider = dest.readString();
        transport_type2_provider = dest.readString();
        transport_type1_price_cents = dest.readInt();
        transport_type2_price_cents = dest.readInt();
        payment_bank_transfer = dest.readByte() != 0;
        payment_cash = dest.readByte() != 0;
        payment_paypal = dest.readByte() != 0;
        payment_cash_on_delivery = dest.readByte() != 0;
        payment_invoice = dest.readByte() != 0;

        payment_cash_on_delivery_price_cents = dest.readInt();
        basic_price_cents = dest.readInt();
        basic_price_amount = dest.readString();
        state = dest.readString();
        vat = dest.readInt();
        custom_seller_identifier = dest.readString();
        gtin = dest.readString();
        transport_type1_number = dest.readInt();
        transport_type2_number = dest.readInt();
        discount_id = dest.readInt();
        friendly_percent_organisation_id = dest.readInt();
        article_template_name = dest.readString();
        transport_time = dest.readString();
        quantity_available = dest.readInt();
        unified_transport = dest.readByte() != 0;
        swappable = dest.readByte() != 0;
        borrowable = dest.readByte() != 0;
        comments_count = dest.readInt();
        original_id = dest.readInt();
    }

    @Override
    public int describeContents() {
        return 0;
    }


    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(id);
        dest.writeString(title);
        dest.writeString(content);
        dest.writeLong(created_at.getTime());
        dest.writeLong(updated_at.getTime());
        dest.writeInt(user_id);
        dest.writeString(condition);
        dest.writeInt(price_cents);
        dest.writeString(currency);
        dest.writeByte((byte) (fair ? 1 : 0));
        dest.writeString(fair_kind);
        dest.writeString(fair_seal);
        dest.writeByte((byte) (ecologic ? 1 : 0));
        dest.writeString(ecologic_seal);
        dest.writeString(ecologic_kind);
        dest.writeByte((byte) (small_and_precious ? 1 : 0));
        dest.writeString(small_and_precious_reason);
        dest.writeByte((byte) (small_and_precious_handmade ? 1 : 0));
        dest.writeInt(quantity);
        dest.writeString(transport_details);
        dest.writeString(payment_details);
        dest.writeInt(friendly_percent);
        dest.writeInt(calculated_fair_cents);
        dest.writeInt(calculated_friendly_cents);
        dest.writeInt(calculated_fee_cents);
        dest.writeString(condition_extra);
        dest.writeByte((byte) (small_and_precious_eu_small_enterprise ? 1 : 0));
        dest.writeString(upcycling_reason);
        dest.writeString(slug);
        dest.writeByte((byte) (transport_pickup ? 1 : 0));
        dest.writeByte((byte) (transport_type1 ? 1 : 0));
        dest.writeByte((byte) (transport_type2 ? 1:0));
        dest.writeString(transport_type1_provider);
        dest.writeString(transport_type2_provider);
        dest.writeInt(transport_type1_price_cents);
        dest.writeInt(transport_type2_price_cents);
        dest.writeByte((byte) (payment_bank_transfer ? 1 : 0));
        dest.writeByte((byte) (payment_cash ? 1 : 0));
        dest.writeByte((byte) (payment_paypal ? 1:0));
        dest.writeByte((byte) (payment_cash_on_delivery ? 1:0));
        dest.writeByte((byte) (payment_invoice ? 1:0));
        dest.writeInt(payment_cash_on_delivery_price_cents);
        dest.writeInt(basic_price_cents);
        dest.writeString(basic_price_amount);
        dest.writeString(state);
        dest.writeInt(vat);
        dest.writeString(custom_seller_identifier);
        dest.writeString(gtin);
        dest.writeInt(transport_type1_number);
        dest.writeInt(transport_type2_number);
        dest.writeInt(discount_id);
        dest.writeInt(friendly_percent_organisation_id);
        dest.writeString(article_template_name);
        dest.writeString(transport_time);
        dest.writeInt(quantity_available);
        dest.writeByte((byte) (unified_transport ? 1:0));
        dest.writeByte((byte) (swappable ? 1:0));
        dest.writeByte((byte) (borrowable ? 1:0));
        dest.writeInt(comments_count);
        dest.writeInt(original_id);
    }

    public static final Parcelable.Creator<Product> CREATOR
            = new Parcelable.Creator<Product>() {
        public Product createFromParcel(Parcel in) {
            return new Product(in);
        }

        public Product[] newArray(int size) {
            return new Product[size];
        }
    };
    // KEEP METHODS END
}
