package de.handler.mobile.android.fairmondo.data.datasource.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SEARCH_SUGGESTION.
*/
public class SearchSuggestionDao extends AbstractDao<SearchSuggestion, Long> {

    public static final String TABLENAME = "SEARCH_SUGGESTION";

    /**
     * Properties of entity SearchSuggestion.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Suggest_text_1 = new Property(1, String.class, "suggest_text_1", false, "SUGGEST_TEXT_1");
        public final static Property Suggest_text_2 = new Property(2, String.class, "suggest_text_2", false, "SUGGEST_TEXT_2");
    };


    public SearchSuggestionDao(DaoConfig config) {
        super(config);
    }
    
    public SearchSuggestionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SEARCH_SUGGESTION' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SUGGEST_TEXT_1' TEXT," + // 1: suggest_text_1
                "'SUGGEST_TEXT_2' TEXT);"); // 2: suggest_text_2
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SEARCH_SUGGESTION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SearchSuggestion entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String suggest_text_1 = entity.getSuggest_text_1();
        if (suggest_text_1 != null) {
            stmt.bindString(2, suggest_text_1);
        }
 
        String suggest_text_2 = entity.getSuggest_text_2();
        if (suggest_text_2 != null) {
            stmt.bindString(3, suggest_text_2);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SearchSuggestion readEntity(Cursor cursor, int offset) {
        SearchSuggestion entity = new SearchSuggestion( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // suggest_text_1
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // suggest_text_2
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SearchSuggestion entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSuggest_text_1(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSuggest_text_2(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SearchSuggestion entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SearchSuggestion entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
