package de.handler.mobile.android.fairmondo.data.datasource.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SEARCH_SUGGESTION.
 */
public class SearchSuggestion {

    private Long id;
    private String suggest_text_1;
    private String suggest_text_2;

    public SearchSuggestion() {
    }

    public SearchSuggestion(Long id) {
        this.id = id;
    }

    public SearchSuggestion(Long id, String suggest_text_1, String suggest_text_2) {
        this.id = id;
        this.suggest_text_1 = suggest_text_1;
        this.suggest_text_2 = suggest_text_2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSuggest_text_1() {
        return suggest_text_1;
    }

    public void setSuggest_text_1(String suggest_text_1) {
        this.suggest_text_1 = suggest_text_1;
    }

    public String getSuggest_text_2() {
        return suggest_text_2;
    }

    public void setSuggest_text_2(String suggest_text_2) {
        this.suggest_text_2 = suggest_text_2;
    }

}
